# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7f32d0dbce58624b595a3bdce660ea650bc804656e77e3e19b3a8841ebd12a1fc2980937c85d9dc955a82365d14fdede46407eb2b4179a726eea5fc5a8a767

test:
  secret_key_base: f019942af8d2ba4af887b3a1e427ec107deb645272b85f0dce29da62673aecdfb12d8fb0576a8015bfaed6b55c99700573b9538f7bb7b849e7c1044fb3f2b70d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
